name = "SimpleHTML"
uuid = "66a626c8-c7d1-41be-af91-a0a35aa73acc"
authors = ["Johan Van Kerckhoven <johan.vankerckhoven@gmail.com> and contributors"]
version = "1.0.3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
